<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

# Lists, Arrays & Dictionaries

## Let’s compare

In [1]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [2]:
import numpy as np

np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [3]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

py and np added in front of the variable for clarity. 
can choose any name for the variables (provided that they are not a Python keyword like for, if).

## Accessing data from a list (or array)

### Python is a zero-indexed language, meaning it starts counting at 0. So if you want to access a particular element in the list (or array), you need to specify the relevant index starting from zero.

In [4]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

py_real_names[0]

'Natasha Romanoff'

In [5]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

py_super_names[0]

'Black Widow'

Using a negative index allows us to count from the back of the list. For instance, using the index -1 will give the last element.

In [6]:
py_super_names[2]    # Forward indexing 
                     # We need to know the size 
                     # beforehand for this to work.

py_super_names[-1]   # Reverse indexing

'Doctor Strange'

## Accessing data from a dictionary

### Remember that dictionaries have a key-value structure.

In [7]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}                  

superhero_info["Natasha Romanoff"]

'Black Widow'

## Higher dimensional lists (same intend as dictionary)

In [8]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

# Lists vs. Arrays

## Size

In [9]:
import numpy as np

py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array
np_array_2d.shape

# Notice the absence of brackets ( ) in shape above. This is because shape is not a function. Instead, it is a property or attribute of the NumPy array.

(10, 2)

In [10]:
len(py_list_2d)
len(np_array_2d)

10

## Arrays are fussy about type

In [11]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [12]:
py_list

[1, 1.5, 'A']

In [13]:
np_array

array(['1', '1.5', 'A'], dtype='<U32')

## Adding a number

In [14]:
import numpy as np

py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

py_list + 10        # Won't work!

TypeError: can only concatenate list (not "int") to list

In [ ]:
import numpy as np

py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array
np_array + 10

array([11, 12, 13, 14, 15])

## Adding another list

In [ ]:
import numpy as np

py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [ ]:
import numpy as np

py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

## Multiplying by a Number

In [ ]:
import numpy as np

py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
import numpy as np

py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

np_array*2

array([ 2,  4,  6,  8, 10])

## Squaring

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

py_list**2                      # Won't work!  

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [ ]:
import numpy as np

py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

np_array**2

array([ 1,  4,  9, 16, 25])

## Asking questions

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

py_list == 3     # Works, but what IS the question?

False

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)       

py_list > 3      # Won't work!

TypeError: '>' not supported between instances of 'list' and 'int'

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)       

np_array == 3  

array([False, False,  True, False, False])

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)    

np_array > 3

array([False, False, False,  True,  True])

## Mathematics

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list) 

sum(py_list)     # sum() is a base Python function
max(py_list)     # max() is a base Python function
min(py_list)     # min() is a base Python function
py_list.sum()   # Won't work!

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

np_array.sum()
np_array.max()
np_array.min()
np_array.mean()
np_array.std()

#all will work

# Exercises & Self-Assessment



Refer to storing data (need) exercises learning portfolio




## Footnotes