<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# Subsetting: Indexing and Slicing

**Subsetting** means to ‘select’.

**Indexing** refers to selecting one element (recall storing (need) content).

**Slicing** refers to selecting a range of elements.

## Lists & Arrays in 1D | Subsetting & Indexing

In [1]:
import numpy as np

py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

| Syntax      | Results                         |                                   | Notes                                    |
|-------------|---------------------------------|-----------------------------------|------------------------------------------|
| `x[0]`      | First element                   | `'a1'`                            |                                          |
| `x[-1]`     | Last element                    | `'j10'`                           |                                          |
| `x[0:3]`    | Index 0 to 2                    | `['a1','b2','c3']`                | Gives  3 − 0 = 3 elements                |
| `x[1:6]`    | Index 1 to 5                    | `['b2','c3','d4','e5','f6']`      | Gives  6 − 1 = 5 elements                |
| `x[1:6:2]`  | Index 1 to 5 in steps of 2      | `['b2','d4','f6']`                | Gives every other of  6 − 1 = 5 elements |
| `x[5:]`     | Index 5 to the end              | `['f6','g7','h8','i9','j10']`     | Gives len(x) − 5 = 5 elements            |
| `x[:5]`     | Index 0 to 5                    | `['a1','b2','c3','d4','e5']`      | Gives  5 − 0 = 5 elements                |
| `x[5:2:-1]` | Index 5 to 3 (i.e., in reverse) | `['f6','e5','d4']`                | Gives  5 − 2 = 3 elements                |
| `x[::-1]`   | Reverses the list               | `['j10','i9','h8',...,'b2','a1']` |                                          |

Remember slicing in Python can be a bit tricky.
**If you slice with `[i:j]`, the slice will start at `i` and end at `j-1`, giving you a total of `j-i` elements.**

## Arrays only | Subsetting by masking

In [2]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask

np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [3]:


np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

**Masking effect where only the `True` subset can be seen**

Remember that subsetting by masking **only** works with NumPy arrays.

In [4]:
np_array[~(np_array > 3)]                 # '~' means 'NOT'

array([1, 2, 3])

In [5]:
np_array[(np_array > 3) & (np_array < 8)] # '&' means 'AND'

array([4, 5, 6, 7])

In [6]:
np_array[(np_array < 3) | (np_array > 8)] # '|' means 'OR'

array([ 1,  2,  9, 10])

**Remember:**
Always use the Bitwise NOT(~), Bitwise OR(|) and Bitwise AND(&) when combining masks with NumPy.
Always use brackets to clarify what you are asking the mask to do.

## Lists & Arrays in 2D | Indexing & Slicing

In [7]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [8]:
py_list_2d[3] # index 3, position 4

[4, 'D']

In [9]:
np_array_2d[3] # index 3, position 4

array(['4', 'D'], dtype='<U21')

In [10]:
py_list_2d[3][0] # index 3, position 4, first element

4

In [11]:
np_array_2d[3, 0] # index 3, position 4, first element

'4'

Notice how the syntax for arrays uses just a single pair of square brackets (`[ ]`).



In [12]:
py_list_2d[:3] # first 3 elements

[[1, 'A'], [2, 'B'], [3, 'C']]

In [13]:
np_array_2d[:3] # first 3 elements

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

In [14]:
py_list_2d[:3][0] # first element of the first 3 elements of the list

[1, 'A']

In [15]:
np_array_2d[:3, 0] # first value of the first 3 elements of the list

array(['1', '2', '3'], dtype='<U21')

In [16]:
py_list_2d[3:6][0]

[4, 'D']

In [17]:
np_array_2d[3:6, 0]

array(['4', '5', '6'], dtype='<U21')

In [18]:
np_array_2d[:, 0] # colon means all elements

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

## Growing lists

In [19]:
x=[1, 2]*5 # extending/growing the list by 5 times of 1,2 
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [20]:
#APPENDING

# Version 1 

x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x

# Version 2 

x=[1]
x+= [2]
x+= [3]
x+= [4]
x

# Version 3

x=[1]
x.append(2)
x.append(3)
x.append(4)
x

# Their execution speeds are different; the version with append() runs about 1.5 times faster than the rest!


[1, 2, 3, 4]

In [21]:
# INCORPORATING MULTIPLE ELEMENTS 

# Version 1 

x = [1, 2, 3]
x += [4, 5, 6]
x

# Version 2

x=[1, 2, 3]
x.extend([4, 5, 6])
x


[1, 2, 3, 4, 5, 6]

In [22]:
# Version 3

x=[1, 2, 3]
x.append([4, 5, 6])
x

[1, 2, 3, [4, 5, 6]]

# Some loose ends

## Tuples

Tuples are similar to lists, except they use ( ) and cannot be changed after creation (i.e., they are immutable).

In [23]:
a=(1, 2, 3)     # Define tuple
print(a[0])    # Access data

1


In [24]:
# The following will NOT work because we cannot change data since tuple is immutable
a[0]=-1
a[0]+= [10]

TypeError: 'tuple' object does not support item assignment

## Be VERY careful when copying

In [ ]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

In [ ]:
# Do this! 

x=[1, 2, 3]
y=x.copy()
z=x.copy()

# Exercises & Self-Assessment

Refer to storing data (good) exercises learning portfolio notebook